### ISSUE TITLE
你好,我执行报错,请问怎么解决?

### ISSUE THREAD

**Issue by cejpo001** [herozhou/vue-framework-wz#24]
提示信息
module.js:538
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\vuetest\wzvue\build\check-versions.js:1:75)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WZ@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WZ@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?
这个我刚学,所以问的问题很低级,但还是请大神指点一下,谢谢

**Comment by cejpo001** [comment]
我重新npm install下就可以了..
